#RAJASHRI SEAL
#SPARKS FOUNDATION DATA SCIENCE AND BUSINESS ANALYTICS INTERNSHIP

#QUESTIONS:
#PREDICT THE PERCENTAGE OF STUDENTS BASED ON THE NUMBER OF STUDY HOURS.
#WHAT WILL BE THE PREDICTED SCORE IF A STUDENT STUDIES FOR 9.25 HOURS PER DAY?

#ANSWERS:

students<-read.csv("https://raw.githubusercontent.com/AdiPersonalWorks/Random/master/student_scores%20-%20student_scores.csv")
View(students)
SCORES<-students$Scores
HOURS<-students$Hours
regression<-lm(SCORES~HOURS)#fits a linear model on the data
regression   #THIS GIVES THE COEFFICIENTS THAT IS THE INTERCEPTS AND THE SLOPES OF THE MODEL
plot(HOURS,SCORES,pch=16,col="violet")
abline(lm(SCORES~HOURS),col="green")
cor(HOURS,SCORES)
SCORES_1<-2.484+(9.776*HOURS)#SCORES_1 GIVES THE PREDICTED VALUE OF SCORES AFTER FITTING THE LINEAR MODEL.
SCORES_1
#now if the hours is 9.25 then
HOURS<-9.25
SCORES_1<-2.484+(9.776*HOURS)
SCORES_1 #GIVES THE SCORE OF A STUDENT WHO STUDIES 9.25 HOURS 
#THANK YOU:)